# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'car_model_form_widget.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.modelInput = QtWidgets.QGroupBox(Form)
        self.modelInput.setObjectName("modelInput")
        self.gridLayout = QtWidgets.QGridLayout(self.modelInput)
        self.gridLayout.setObjectName("gridLayout")
        self.t = QtWidgets.QLineEdit(self.modelInput)
        self.t.setObjectName("t")
        self.gridLayout.addWidget(self.t, 7, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.modelInput)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.modelInput)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 4, 1, 1)
        self.suspension_spring = QtWidgets.QLineEdit(self.modelInput)
        self.suspension_spring.setObjectName("suspension_spring")
        self.gridLayout.addWidget(self.suspension_spring, 2, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.modelInput)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 4, 1, 1)
        self.car_body_mass = QtWidgets.QLineEdit(self.modelInput)
        self.car_body_mass.setObjectName("car_body_mass")
        self.gridLayout.addWidget(self.car_body_mass, 0, 5, 1, 1)
        self.car_speed = QtWidgets.QLineEdit(self.modelInput)
        self.car_speed.setObjectName("car_speed")
        self.gridLayout.addWidget(self.car_speed, 1, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 12, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.modelInput)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.modelInput)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 4, 1, 1)
        self.wheel_mass = QtWidgets.QLineEdit(self.modelInput)
        self.wheel_mass.setObjectName("wheel_mass")
        self.gridLayout.addWidget(self.wheel_mass, 4, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.modelInput)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.modelInput)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.modelInput)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 4, 1, 1)
        self.suspension_shock_absorber = QtWidgets.QLineEdit(self.modelInput)
        self.suspension_shock_absorber.setObjectName("suspension_shock_absorber")
        self.gridLayout.addWidget(self.suspension_shock_absorber, 3, 5, 1, 1)
        self.ramp_angle = QtWidgets.QLineEdit(self.modelInput)
        self.ramp_angle.setObjectName("ramp_angle")
        self.gridLayout.addWidget(self.ramp_angle, 6, 5, 1, 1)
        self.tire_spring_constant = QtWidgets.QLineEdit(self.modelInput)
        self.tire_spring_constant.setObjectName("tire_spring_constant")
        self.gridLayout.addWidget(self.tire_spring_constant, 5, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 11, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 10, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 9, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 3, 1, 1)
        self.calculate = QtWidgets.QPushButton(self.modelInput)
        self.calculate.setObjectName("calculate")
        self.gridLayout.addWidget(self.calculate, 8, 5, 1, 1)
        self.verticalLayout.addWidget(self.modelInput)
        self.modelOutput = QtWidgets.QGroupBox(Form)
        self.modelOutput.setObjectName("modelOutput")
        self.formLayout = QtWidgets.QFormLayout(self.modelOutput)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout.addWidget(self.modelOutput)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.modelInput.setTitle(_translate("Form", "Model Inputs"))
        self.label_16.setText(_translate("Form", "Car Body Mass (m1, Kg)"))
        self.label_12.setText(_translate("Form", "Car Speed (kph)"))
        self.label_13.setText(_translate("Form", "Suspension Shock Absorber (c1, N*s/m)"))
        self.label_15.setText(_translate("Form", "t, max plot (s)"))
        self.label_14.setText(_translate("Form", "Suspension Spring (k1, N/m)"))
        self.label_10.setText(_translate("Form", "Tire Spring Constant (k2, N/m)"))
        self.label_11.setText(_translate("Form", "Wheel Mass (m2, kg)"))
        self.label_9.setText(_translate("Form", "Ramp Angle (deg)"))
        self.calculate.setText(_translate("Form", "Calculate"))
        self.modelOutput.setTitle(_translate("Form", "Output Graph"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
